#!/usr/bin/env python3
"""LLM session logger for this repository (from the StoreClaudeWork template).

Every Claude Code session that touches this repository is archived under
``llm-logs/<session_id>/`` and indexed in ``llm-logs/sessions.csv``.  This
single script implements all the hook actions so the shell hooks in
``.claude/hooks/`` stay one-liners.

Sub-commands (each reads the Claude Code hook JSON payload on stdin
unless ``--transcript``/``--session-id`` are given explicitly):

  session-start   register the session in sessions.csv (SessionStart hook)
  prompt          append the submitted prompt to prompt-log.csv and to the
                  session's prompts.csv in real time (UserPromptSubmit hook)
  archive         copy the transcript into llm-logs/<session_id>/, rebuild
                  the session's human-readable files and the global index,
                  and ``git add llm-logs`` (Stop + SessionEnd hooks)
  commit          commit ONLY llm-logs/ and push to the current branch
                  (SessionEnd hook)
  index           rebuild llm-logs/SESSIONS.md and every session's
                  PROMPTS-AND-RESPONSES.md from the archived transcripts

Layout of one session folder::

  llm-logs/<session_id>/
      transcript.jsonl              full Claude Code transcript (ground truth)
      transcript.resumed.jsonl      continuation, if the session was resumed
                                    in a fresh container (compacted transcript)
      session.json                  metadata: start/end, models, tools, branch
      prompts.csv                   one row per human prompt (from transcript)
      PROMPTS-AND-RESPONSES.md      every prompt in full and the assistant's
                                    text replies, readable without an LLM

The transcript JSONL is an internal Claude Code format and may change; the
CSV and Markdown files are the stable, human-readable record.  Never edit
the generated files by hand - rerun ``python3 llm-logs/tools/llmlog.py index``.
"""
import csv
import datetime as dt
import getpass
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = os.path.dirname(HERE)                      # .../llm-logs
# The repository root is where this script lives, not CLAUDE_PROJECT_DIR:
# a session started in a parent folder (several repos in one cloud session)
# must still archive into this repository when the script is run by hand.
ROOT = os.path.dirname(LOG)
SESSIONS_CSV = os.path.join(LOG, "sessions.csv")
PROMPT_LOG_CSV = os.path.join(LOG, "prompt-log.csv")
SESSIONS_HEADER = ["start_date", "start_time_utc", "session_id", "user",
                   "source", "git_branch", "prompts", "first_prompt", "topic"]
PROMPT_LOG_HEADER = ["date", "time_utc", "user", "session_id", "prompt_text"]
MAXLEN = 200
GENERATED_NOTE = "<!-- generated by llm-logs/tools/llmlog.py - do not edit, rerun `index` -->"


# ----------------------------------------------------------------- helpers
def now_utc():
    return dt.datetime.now(dt.timezone.utc)


def username():
    return (os.environ.get("PROMPT_LOG_USER")
            or os.environ.get("CLAUDE_CODE_USER_EMAIL")
            or getpass.getuser())


def source():
    if os.environ.get("CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE"):
        return "claude-code-remote"
    return "claude-code"


def git(*args):
    try:
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                              text=True, check=False).stdout.strip()
    except Exception:
        return ""


def read_payload(args):
    """Hook payload from stdin, merged with explicit command-line overrides."""
    data = {}
    # Hooks always pipe a JSON payload on stdin.  When run by hand with
    # --session-id / --transcript, do not touch stdin (it may block forever).
    if not (args.session_id or args.transcript) and not sys.stdin.isatty():
        raw = sys.stdin.read()
        if raw.strip():
            try:
                data = json.loads(raw)
            except Exception:
                data = {}
    if args.session_id:
        data["session_id"] = args.session_id
    if args.transcript:
        data["transcript_path"] = args.transcript
    if not data.get("session_id"):
        data["session_id"] = os.environ.get("CLAUDE_CODE_SESSION_ID", "")
    if not data.get("transcript_path") and data.get("session_id"):
        # Default Claude Code location: ~/.claude/projects/<mangled cwd>/<id>.jsonl
        for base in (os.environ.get("CLAUDE_PROJECT_DIR"), ROOT):
            if not base:
                continue
            mangled = re.sub(r"[^A-Za-z0-9]", "-", base)
            cand = os.path.expanduser(os.path.join("~", ".claude", "projects", mangled,
                                                   data["session_id"] + ".jsonl"))
            if os.path.isfile(cand):
                data["transcript_path"] = cand
                break
    return data


def clean(text, maxlen=MAXLEN):
    text = re.sub(r"<[^>]{1,60}>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > maxlen:
        text = text[: maxlen - 1].rstrip() + "…"
    return text


def read_csv(path, header):
    rows = []
    if os.path.exists(path):
        with open(path, encoding="utf-8", newline="") as f:
            rows = list(csv.reader(f))
    if not rows:
        rows = [header]
    return rows


def write_csv(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        csv.writer(f).writerows(rows)


# -------------------------------------------------------- transcript parsing
def _text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(c.get("text", "") for c in content
                         if isinstance(c, dict) and c.get("type") == "text")
    return ""


def is_human_prompt(obj):
    """True for a transcript record that is a prompt typed by the human."""
    if obj.get("type") != "user" or obj.get("isSidechain") or obj.get("isMeta"):
        return False
    msg = obj.get("message") or {}
    content = msg.get("content")
    if isinstance(content, list):
        kinds = {c.get("type") for c in content if isinstance(c, dict)}
        if "tool_result" in kinds:
            return False
    txt = _text_of(content).strip()
    if not txt:
        return False
    # skip hook noise, system-injected turns and interruption markers
    if txt.startswith(("<", "Caveat:", "[Request interrupted")):
        return False
    return True


def parse_transcript(path):
    """Return a dict with turns, timestamps, models, tool counts."""
    turns = []          # list of {"ts", "prompt", "responses": [...], "tools": {...}}
    models, tools = set(), {}
    first_ts = last_ts = None
    version = branch = None
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except Exception:
                continue
            ts = obj.get("timestamp")
            if ts:
                first_ts = first_ts or ts
                last_ts = ts
            version = obj.get("version") or version
            branch = obj.get("gitBranch") or branch
            typ = obj.get("type")
            if typ == "user":
                if is_human_prompt(obj):
                    turns.append({"ts": ts, "prompt": _text_of(obj["message"]["content"]).strip(),
                                  "responses": [], "tools": {}})
            elif typ == "assistant" and not obj.get("isSidechain"):
                msg = obj.get("message") or {}
                if msg.get("model"):
                    models.add(msg["model"])
                for c in msg.get("content", []) or []:
                    if not isinstance(c, dict):
                        continue
                    if c.get("type") == "text" and c.get("text", "").strip():
                        if turns:
                            turns[-1]["responses"].append((ts, c["text"].strip()))
                    elif c.get("type") == "tool_use":
                        name = c.get("name", "?")
                        tools[name] = tools.get(name, 0) + 1
                        if turns:
                            turns[-1]["tools"][name] = turns[-1]["tools"].get(name, 0) + 1
    return {"turns": turns, "first_ts": first_ts, "last_ts": last_ts,
            "models": sorted(models), "tools": tools, "version": version,
            "git_branch": branch}


def session_parts(sdir):
    return [p for p in (os.path.join(sdir, "transcript.jsonl"),
                        os.path.join(sdir, "transcript.resumed.jsonl"))
            if os.path.exists(p)]


def parse_session(sdir):
    info = {"turns": [], "first_ts": None, "last_ts": None, "models": set(),
            "tools": {}, "version": None, "git_branch": None, "bytes": 0}
    for p in session_parts(sdir):
        d = parse_transcript(p)
        info["turns"] += d["turns"]
        info["first_ts"] = info["first_ts"] or d["first_ts"]
        info["last_ts"] = d["last_ts"] or info["last_ts"]
        info["models"] |= set(d["models"])
        for k, v in d["tools"].items():
            info["tools"][k] = info["tools"].get(k, 0) + v
        info["version"] = d["version"] or info["version"]
        info["git_branch"] = d["git_branch"] or info["git_branch"]
        info["bytes"] += os.path.getsize(p)
    info["models"] = sorted(info["models"])
    return info


def hhmm(ts):
    return (ts or "")[11:16]


def duration(a, b):
    try:
        fmt = "%Y-%m-%dT%H:%M:%S"
        mins = int((dt.datetime.strptime(b[:19], fmt)
                    - dt.datetime.strptime(a[:19], fmt)).total_seconds() // 60)
        return f"{mins} min" if mins < 60 else f"{mins // 60} h {mins % 60} min"
    except Exception:
        return "?"


# --------------------------------------------------------- session index csv
def upsert_session_row(sid, start_ts=None, first_prompt=None, nprompts=None,
                       branch=None):
    rows = read_csv(SESSIONS_CSV, SESSIONS_HEADER)
    header = rows[0]
    idx = {h: i for i, h in enumerate(header)}
    found = None
    for r in rows[1:]:
        while len(r) < len(header):
            r.append("")
        if r[idx["session_id"]] == sid:
            found = r
    if found is None:
        found = [""] * len(header)
        found[idx["session_id"]] = sid
        found[idx["user"]] = username()
        found[idx["source"]] = source()
        found[idx["topic"]] = "untagged"
        rows.append(found)
    if start_ts and not found[idx["start_date"]]:
        found[idx["start_date"]] = start_ts[:10]
        found[idx["start_time_utc"]] = start_ts[11:19]
    if branch and not found[idx["git_branch"]]:
        found[idx["git_branch"]] = branch
    if first_prompt and not found[idx["first_prompt"]]:
        found[idx["first_prompt"]] = clean(first_prompt, 120)
    if nprompts is not None:
        found[idx["prompts"]] = str(nprompts)
    rows[1:] = sorted(rows[1:], key=lambda r: (r[idx["start_date"]], r[idx["start_time_utc"]]))
    write_csv(SESSIONS_CSV, rows)
    return dict(zip(header, found))


# ------------------------------------------------------------- generators
def write_session_files(sid):
    sdir = os.path.join(LOG, sid)
    info = parse_session(sdir)
    meta_row = upsert_session_row(sid, start_ts=info["first_ts"],
                                  first_prompt=(info["turns"][0]["prompt"] if info["turns"] else None),
                                  nprompts=len(info["turns"]), branch=info["git_branch"])
    # session.json
    meta = {
        "session_id": sid,
        "start_utc": info["first_ts"], "last_event_utc": info["last_ts"],
        "span": duration(info["first_ts"], info["last_ts"]),
        "prompts": len(info["turns"]),
        "models": info["models"],
        "tool_use_counts": dict(sorted(info["tools"].items(), key=lambda kv: -kv[1])),
        "claude_code_version": info["version"],
        "git_branch": info["git_branch"],
        "user": meta_row.get("user"), "source": meta_row.get("source"),
        "topic": meta_row.get("topic"),
        "transcript_files": [os.path.basename(p) for p in session_parts(sdir)],
        "transcript_bytes": info["bytes"],
    }
    with open(os.path.join(sdir, "session.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
        f.write("\n")
    # prompts.csv
    rows = [["n", "date", "time_utc", "prompt_text"]]
    for i, t in enumerate(info["turns"], 1):
        rows.append([i, (t["ts"] or "")[:10], (t["ts"] or "")[11:19], t["prompt"]])
    write_csv(os.path.join(sdir, "prompts.csv"), rows)
    # prompt-log.csv: back-fill prompts the UserPromptSubmit hook did not see
    # (sessions that ran before the hooks existed, or hook failures)
    plog = read_csv(PROMPT_LOG_CSV, PROMPT_LOG_HEADER)
    seen = {(r[3], r[4]) for r in plog[1:] if len(r) >= 5}
    added = False
    for t in info["turns"]:
        if (sid, t["prompt"]) not in seen:
            plog.append([(t["ts"] or "")[:10], (t["ts"] or "")[11:19],
                         meta_row.get("user") or username(), sid, t["prompt"]])
            seen.add((sid, t["prompt"]))
            added = True
    if added:
        plog[1:] = sorted(plog[1:], key=lambda r: (r[0], r[1]))
        write_csv(PROMPT_LOG_CSV, plog)
    # PROMPTS-AND-RESPONSES.md
    out = [GENERATED_NOTE, f"# Session `{sid}`", ""]
    out.append(f"- Started (UTC): {info['first_ts'] or '?'}  ")
    out.append(f"- Last event (UTC): {info['last_ts'] or '?'} (span {meta['span']})  ")
    out.append(f"- User: {meta['user']}; source: {meta['source']}; branch: `{info['git_branch']}`  ")
    out.append(f"- Models: {', '.join(info['models']) or '?'}; Claude Code {info['version'] or '?'}  ")
    out.append(f"- Prompts: {len(info['turns'])}; transcript: "
               + ", ".join(meta["transcript_files"]) + f" ({info['bytes'] / 1e6:.1f} MB)")
    out.append("")
    out.append("This file is derived from the transcript for readers without an LLM. "
               "Prompts are verbatim; responses are the assistant's text messages "
               "(tool calls and their output are only summarised - see the JSONL for those).")
    out.append("")
    for i, t in enumerate(info["turns"], 1):
        out.append(f"## Prompt {i} - {(t['ts'] or '')[:19].replace('T', ' ')} UTC")
        out.append("")
        out.append("```text")
        out.append(t["prompt"].replace("```", "'''"))
        out.append("```")
        out.append("")
        if t["tools"]:
            used = ", ".join(f"{k} ×{v}" for k, v in sorted(t["tools"].items(), key=lambda kv: -kv[1]))
            out.append(f"_Tools used in this turn: {used}_")
            out.append("")
        out.append(f"### Response {i}")
        out.append("")
        if not t["responses"]:
            out.append("_(no text response recorded - see transcript)_")
        for ts, txt in t["responses"]:
            out.append(f"**[{hhmm(ts)} UTC]**")
            out.append("")
            out.append(txt)
            out.append("")
        out.append("")
    with open(os.path.join(sdir, "PROMPTS-AND-RESPONSES.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    return meta


def write_index():
    sessions = []
    for name in sorted(os.listdir(LOG)):
        sdir = os.path.join(LOG, name)
        if os.path.isdir(sdir) and session_parts(sdir):
            sessions.append((name, write_session_files(name)))
    rows = {r["session_id"]: r for r in csv.DictReader(open(SESSIONS_CSV, encoding="utf-8"))} \
        if os.path.exists(SESSIONS_CSV) else {}
    sessions.sort(key=lambda s: s[1]["start_utc"] or "")
    out = [GENERATED_NOTE, "# LLM session log - human-readable index", ""]
    out.append("Every Claude Code session run in this repository is archived here: one "
               "folder per session (named by session id) holding the full transcript, "
               "the prompts as CSV and a readable `PROMPTS-AND-RESPONSES.md`. "
               "`sessions.csv` is the index of sessions and `prompt-log.csv` the "
               "real-time log of every prompt. See `llm-logs/README.md` for the design.")
    out.append("")
    out.append("| Started (UTC) | Topic | Session id | Prompts | Span | Branch | Transcript |")
    out.append("|---|---|---|---|---|---|---|")
    for sid, m in sessions:
        topic = rows.get(sid, {}).get("topic", "untagged")
        out.append(f"| {(m['start_utc'] or '')[:16].replace('T', ' ')} | {topic} | "
                   f"[`{sid[:8]}…`]({sid}/PROMPTS-AND-RESPONSES.md) | {m['prompts']} | "
                   f"{m['span']} | `{m['git_branch'] or ''}` | {m['transcript_bytes'] / 1e6:.1f} MB |")
    out.append("")
    for sid, m in sessions:
        out.append(f"## {(m['start_utc'] or '')[:10]} - `{sid}`")
        out.append("")
        out.append(f"Topic: {rows.get(sid, {}).get('topic', 'untagged')}. "
                   f"Models: {', '.join(m['models']) or '?'}. "
                   f"Tools: " + (", ".join(f"{k} ×{v}" for k, v in list(m['tool_use_counts'].items())[:8]) or "none") + ".")
        out.append("")
        sdir = os.path.join(LOG, sid)
        try:
            with open(os.path.join(sdir, "prompts.csv"), encoding="utf-8", newline="") as f:
                for r in list(csv.reader(f))[1:]:
                    out.append(f"{r[0]}. {r[2][:5]} - {clean(r[3])}")
        except Exception:
            pass
        out.append("")
    with open(os.path.join(LOG, "SESSIONS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))


# ---------------------------------------------------------------- commands
def cmd_session_start(data):
    sid = data.get("session_id")
    if not sid:
        return
    upsert_session_row(sid, start_ts=now_utc().strftime("%Y-%m-%dT%H:%M:%S"),
                       branch=git("rev-parse", "--abbrev-ref", "HEAD"))


def cmd_prompt(data):
    sid = data.get("session_id", "")
    prompt = data.get("prompt", "")
    # System-injected turns (task notifications, hook output, "<system-reminder>")
    # also fire UserPromptSubmit; they are not human prompts.
    if not prompt.strip() or prompt.lstrip().startswith(("<", "Caveat:", "[Request interrupted")):
        return
    now = now_utc()
    rows = read_csv(PROMPT_LOG_CSV, PROMPT_LOG_HEADER)
    rows.append([now.strftime("%Y-%m-%d"), now.strftime("%H:%M:%S"), username(), sid, prompt])
    write_csv(PROMPT_LOG_CSV, rows)
    if sid:
        upsert_session_row(sid, start_ts=now.strftime("%Y-%m-%dT%H:%M:%S"),
                           first_prompt=prompt, branch=git("rev-parse", "--abbrev-ref", "HEAD"))


def cmd_archive(data):
    sid = data.get("session_id")
    tp = data.get("transcript_path")
    if not sid or not tp or not os.path.isfile(tp):
        return
    sdir = os.path.join(LOG, sid)
    os.makedirs(sdir, exist_ok=True)
    dest = os.path.join(sdir, "transcript.jsonl")
    # A session resumed in a fresh container rebuilds a SMALLER (compacted)
    # transcript.  Never clobber a larger archive: write the continuation to
    # transcript.resumed.jsonl instead.  Both files belong to the session.
    if os.path.exists(dest) and os.path.getsize(dest) > os.path.getsize(tp):
        dest = os.path.join(sdir, "transcript.resumed.jsonl")
    shutil.copy2(tp, dest)
    write_index()
    git("add", "llm-logs")


def cmd_commit(data):
    write_index()
    git("add", "llm-logs")
    if git("diff", "--cached", "--name-only", "--", "llm-logs"):
        git("commit", "-o", "llm-logs", "-m", "llm-logs: archive session log (automatic)")
        branch = git("rev-parse", "--abbrev-ref", "HEAD")
        if branch and branch != "HEAD":
            git("push", "origin", f"HEAD:{branch}")


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["session-start", "prompt", "archive", "commit", "index"])
    ap.add_argument("--session-id")
    ap.add_argument("--transcript")
    args = ap.parse_args()
    if args.command == "index":
        write_index()
        return
    data = read_payload(args)
    {"session-start": cmd_session_start, "prompt": cmd_prompt,
     "archive": cmd_archive, "commit": cmd_commit}[args.command](data)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # a hook must never block Claude Code
        sys.stderr.write(f"llmlog: {exc}\n")
    sys.exit(0)
